### PR TITLE
Added exception handling for failed request

### PR DESCRIPTION
**Pull request by raheelkhan**
I was experiencing white screen when trying to access one url. So i added a exception handler if curl response is false.

### CODE REVIEW

**Comment by sylouuu** [comment]
Hey @raheelkhan,

What have you done to get `false` for `$response`?

Bests

**Comment by raheelkhan** [comment]
Hi,

This is how i tried

```
require 'vendor/autoload.php';

// Namespace shortcut
use sylouuu\Curl\Method as Curl;

$url = "https://news.ycombinator.com/";

$request = new Curl\Get( $url );
$request->send();
echo $request->getResponse();
```

**Comment by sylouuu** [comment]
It works for me. If I perform a `var_dump($request->getResponse());`:

```
string(28326) "<html op="news"><head><meta name="referrer" content="origin"><link rel="stylesheet" type="text/css" href="news.css?gTB73KZkvMRlaxwe242h">
        <link rel="shortcut icon" href="favicon.ico">
          <link rel="alternate" type="application/rss+xml" title="RSS" href="rss">
        <script type="text/javascript">
function hide(id) {
  var el = document.getElementById(id);
  if (el) { el.style.visibility = 'hidden'; }
}
function vote(node) {
  var v = node.id.split(/_/);
  var item = v[1];
  hide('up_'   + item);
  hide('down_' + item);
  var ping = new Image();
  ping.src = node.href;
  return false;
  }
    </script><title>Hacker News</title></head><body><center><table id="hnmain" border="0" cellpadding="0" cellspacing="0" width="85%" bgcolor="#f6f6ef">
        <tr><td bgcolor="#ff6600"><table border="0" cellpadding="0" cellspacing="0" width="100%" style="padding:2px"><tr><td style="width:18px;padding-right:4px"><a href="http://www.ycombinator.com"><img src="y18.gif" width="18" height="18" style="border:1px #ffffff solid;"></a></td>
                  <td style="line-height:12pt; height:10px;"><span class="pagetop">
                              <b><a href="news">Hacker News</a></b><img src="s.gif" height="1" width="10"><a href="newest">new</a> | <a href="newcomments">comments</a> | <a href="show">show</a> | <a href="ask">ask</a> | <a href="jobs">jobs</a> | <a href="submit">submit</a></span></td><td style="text-align:right;padding-right:4px;"><span class="pagetop">
                              <a href="login?goto=news">login</a>
                          </span></td>
              </tr></table></td></tr>
<tr style="height:10px"></tr><tr><td>
    <table border="0" cellpadding="0" cellspacing="0">
            <tr class='athing'>
      <td align="right" valign="top" class="title"><span class="rank">1.</span></td>      <td><center><a id="up_9677306" href="vote?for=9677306&amp;dir=up&amp;goto=news"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="deadmark"></span><a href="h"...
```

**Comment by sylouuu** [comment]
Any answer @raheelkhan?

**Comment by raheelkhan** [comment]
Did you deliberately failed the curl and try ? In my case it was failing
silently

**Comment by sylouuu** [comment]
@raheelkhan I don't know how to deliberately create an error to perform a unit test. My `getResponse()` always returns a content other than `false`.

**Comment by sylouuu** [comment]
I close this PR.

Maybe I'll implement this behavior later.

Thank's.

**Pull request closed without merging**
